import React from 'react';
import Container from './Container';

export default {
  component: Container,
  title: 'Components/Container',
};

export const withText = args => (
  <Container {...args}>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed risus ultricies tristique nulla. Nulla aliquet enim tortor at auctor urna. Non consectetur a erat nam at lectus urna. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Sem viverra aliquet eget sit amet tellus cras. Adipiscing tristique risus nec feugiat in. Ultrices in iaculis nunc sed. Risus ultricies tristique nulla aliquet enim tortor at. Enim facilisis gravida neque convallis a cras semper auctor neque. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Aenean vel elit scelerisque mauris. Aenean et tortor at risus viverra adipiscing at in. Venenatis cras sed felis eget velit aliquet sagittis. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci.</p>
    <p>Lorem dolor sed viverra ipsum nunc aliquet bibendum. Suscipit tellus mauris a diam. Facilisis leo vel fringilla est ullamcorper eget. Quam pellentesque nec nam aliquam sem et tortor consequat. Placerat duis ultricies lacus sed turpis. Elit pellentesque habitant morbi tristique senectus et. A pellentesque sit amet porttitor eget dolor. Arcu cursus euismod quis viverra. Placerat orci nulla pellentesque dignissim enim sit amet. Ullamcorper morbi tincidunt ornare massa eget egestas. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Phasellus vestibulum lorem sed risus ultricies tristique. Parturient montes nascetur ridiculus mus.</p>
    <p>Consectetur purus ut faucibus pulvinar elementum integer enim. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Amet justo donec enim diam. Sed faucibus turpis in eu mi bibendum neque egestas. Aliquam etiam erat velit scelerisque in dictum non. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Sit amet volutpat consequat mauris nunc. Suspendisse in est ante in. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Hendrerit gravida rutrum quisque non tellus orci. A arcu cursus vitae congue mauris rhoncus aenean vel. Felis imperdiet proin fermentum leo vel orci porta. Sed odio morbi quis commodo odio aenean sed adipiscing. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Diam volutpat commodo sed egestas egestas fringilla phasellus. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Massa sapien faucibus et molestie ac feugiat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Et netus et malesuada fames ac turpis egestas integer eget. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis.</p>
    <p>Rutrum quisque non tellus orci ac auctor augue. Tincidunt vitae semper quis lectus nulla at. Tellus cras adipiscing enim eu turpis. Imperdiet proin fermentum leo vel orci. Venenatis lectus magna fringilla urna. Purus in mollis nunc sed. Id semper risus in hendrerit gravida rutrum quisque non. Quis viverra nibh cras pulvinar mattis. Imperdiet proin fermentum leo vel. Nec dui nunc mattis enim ut tellus elementum sagittis vitae.</p>
    <p>Bibendum neque egestas congue quisque egestas. Amet nisl suscipit adipiscing bibendum est. Magna sit amet purus gravida. Tempus urna et pharetra pharetra massa massa ultricies mi. Diam phasellus vestibulum lorem sed risus. Id semper risus in hendrerit gravida rutrum quisque non. Mauris vitae ultricies leo integer malesuada. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Ante in nibh mauris cursus mattis molestie a. Amet est placerat in egestas erat imperdiet sed euismod. Amet commodo nulla facilisi nullam. Sit amet risus nullam eget felis. Arcu dui vivamus arcu felis bibendum ut tristique.</p>
  </Container>
)
