import { ChunkExtractor, ChunkExtractorManager } from '@loadable/server';
import path from 'path';
import config from '../../config';

export default () => {
  // This is the stats file generated by webpack loadable plugin
  const statsFile = path.resolve('./build/loadable-stats.json');

  // We create an extractor from the statsFile
  const extractor = new ChunkExtractor({ statsFile });

  return {
    Component: (args) => (
      <ChunkExtractorManager extractor={extractor} {...args} />
    ),
    attributes: () => ({
      link: extractor.getLinkTags(),
      style: extractor.getStyleTags(),
      script: config.get('csr') ? extractor.getScriptTags() : '',
    }),
  };
};
